# Generated by Django 5.0.3 on 2024-05-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_myapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyApplication',
        ),
    ]
